In [1]:
import numpy as np

In [2]:
np.empty((2,5,7))

array([[[ 1.33856858e-152,  1.38202650e+267,  1.13279038e-153,
          2.46090675e-154,  2.34785694e+251,  1.27849494e-152,
          3.92883360e-027],
        [ 7.01413727e-009,  1.38202650e+267,  2.31634003e-152,
          6.01334637e-154,  2.42774684e-154,  7.52158441e-313,
          7.20881811e+159],
        [ 2.75490011e-085,  6.01099957e+175,  2.09778968e-153,
          1.75489917e-152,  1.27966001e-152,  3.98384720e+252,
          6.60703074e+265],
        [ 8.87297278e+247,  1.16034649e+200,  2.45886224e+198,
          3.32230853e+257,  4.04805490e-309,  8.72565038e+252,
          1.44506353e+214],
        [ 4.61248911e-303,  1.93040320e+241,  3.28357629e-310,
          5.03961303e-266,  8.19148733e+247,  7.48762101e-218,
          3.98384720e+252]],

       [[ 7.28297411e+199,  3.32653128e-111,  3.00686030e-051,
          1.28264699e-312,  1.35981565e-307,  1.33360317e+241,
          1.01855798e-311],
        [ 5.11078544e-269,  1.83160642e-260,  1.92853460e-309,
          5

In [3]:
ex_a=np.arange(10).reshape(2,5)

In [4]:
np.ones_like

<function numpy.core.numeric.ones_like(a, dtype=None, order='K', subok=True)>

In [10]:
np.full((5,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
x=np.arange(10)
x.dtype

dtype('int32')

In [15]:
x.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
arr=np.arange(10)
arr_2 = np.arange(11,21)
print(arr)
print(arr_2)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]


In [17]:
arr>arr_2

array([False, False, False, False, False, False, False, False, False,
       False])

In [18]:
arr=np.array([10,1,5,1,8])
arr_2 = np.array([10,2,1,5,10])
print(arr)
print(arr_2)

[10  1  5  1  8]
[10  2  1  5 10]


In [19]:
arr>arr_2

array([False, False,  True, False, False])

In [20]:
in_arr=np.arange(81).reshape((9,9))

In [21]:
in_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [22]:
in_arr[3,5]

32

In [23]:
in_arr[3][5]

32

In [19]:
##in_arrarr_2[row,column]

In [26]:
in_arr[3:7,3:7]=np.zeros(16).reshape(4,4)

In [27]:
in_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29,  0,  0,  0,  0, 34, 35],
       [36, 37, 38,  0,  0,  0,  0, 43, 44],
       [45, 46, 47,  0,  0,  0,  0, 52, 53],
       [54, 55, 56,  0,  0,  0,  0, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [28]:
in_arr[3:7,3:7]=np.zeros(16).reshape(4,4)

In [31]:
in_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29,  0,  0,  0,  0, 34, 35],
       [36, 37, 38,  0,  0,  0,  0, 43, 44],
       [45, 46, 47,  0,  0,  0,  0, 52, 53],
       [54, 55, 56,  0,  0,  0,  0, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])