In [14]:
def foo():
    try:
        print(1)
    finally:
        print(2)
foo()

1
2


In [15]:
def foo():
    return total + 1
total = 0
print(foo())

1


In [16]:
a=[1,2,3,5,6,5,7,8,6]
b=set(a)

In [17]:
b

{1, 2, 3, 5, 6, 7, 8}

In [18]:
import numpy as np

In [19]:
a=np.arange(20).reshape(4,5)
b=np.arange(21,41).reshape(4,5)

In [20]:
print(a)
print("================")
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [21]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [22]:
np.concatenate((a,b),axis=1)#x axis take as 0 or Y axis take as 1

array([[ 0,  1,  2,  3,  4, 21, 22, 23, 24, 25],
       [ 5,  6,  7,  8,  9, 26, 27, 28, 29, 30],
       [10, 11, 12, 13, 14, 31, 32, 33, 34, 35],
       [15, 16, 17, 18, 19, 36, 37, 38, 39, 40]])

In [23]:
np.vstack((a,b))#V means vertical Stack nd H means Horizontal and for deapth use D     STACK COMES IN ALL V , H , D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [24]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 21, 22, 23, 24, 25],
       [ 5,  6,  7,  8,  9, 26, 27, 28, 29, 30],
       [10, 11, 12, 13, 14, 31, 32, 33, 34, 35],
       [15, 16, 17, 18, 19, 36, 37, 38, 39, 40]])

In [25]:
np.dstack((a,b))

array([[[ 0, 21],
        [ 1, 22],
        [ 2, 23],
        [ 3, 24],
        [ 4, 25]],

       [[ 5, 26],
        [ 6, 27],
        [ 7, 28],
        [ 8, 29],
        [ 9, 30]],

       [[10, 31],
        [11, 32],
        [12, 33],
        [13, 34],
        [14, 35]],

       [[15, 36],
        [16, 37],
        [17, 38],
        [18, 39],
        [19, 40]]])

# TRANSPOSE

In [26]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
np.transpose(a)#it turns horizontal (Rows) to vertical (columns)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Boolean Array

In [29]:
names = (["junaid",'Ahmed','Zayan',"Mothasim"])
print(names)
print("-------------")
print(data)
x = names == "Junaid"
print(x)
 data[names < "junaid"]

IndentationError: unexpected indent (<ipython-input-29-a68361d57c96>, line 7)